### ISSUE TITLE
Agent appears twice in hazard choice

### ISSUE THREAD

**Issue by devouges** [usmcgeek/mer#10]
In file "card fields", I think the first "agent entry can be removed.  I removed it in my version and it works ok. 

		_**choice: Agent
		choice:**_
			name: Agent
			choice: Haz
			choice: Minion

**Comment by usmcgeek** [comment]
Closing this one - It would apply to the other repo - but I'm also leaving existing menu choices to ensure backwards compatibility with sets from the previous version of Mse
