### ISSUE TITLE
Some text bugs for some cards on the classic style

### ISSUE THREAD

**Issue by PIC16f841** [usmcgeek/mer#16]
Hi,
The following cards have issues : 

- Missing text at the end of the last sentence of the card : Tolfalas (against the shadow), Lost tome (dark minions), No waiting to wonder (dark minions)
- Swordmaster (wizards) : Missing the promo crown symbol
- Ruined Signal Tower (wizards) and Gold Hill (dragons) : art by text at the bottom have a very small top margin

These only seem to be present on the classic style. Remastered style looks fine

**Comment by PIC16f841** [comment]
Missing texts : 

- Tolfalas : add "revealed as its new site"
- Lost tome : add "turn"
- No waiting to wonders : add "strike)."

**Comment by usmcgeek** [comment]
Classic Style is in testing - there are some text errors and such.  Mainly just present for reference.  I only focus on maintaining the remastered styles.
