### ISSUE TITLE
DC Erratum version

### ISSUE THREAD

**Issue by thenamelessthing** [usmcgeek/mer#17]
Hi, great job on all the graphics enhancement on all the cards.

I was wondering if it would be possible to also create a version of the  cards containing the DC Erratum version (available on cardnum). I'm willing to contribute to the effort if needed or even take care of making them, if you can explain how to do it.

Here is the list of cards that have a revised version to allow a better integration with the DC series.

Bert
Tom
Two-headed troll
William
A short rest
Adunaphel
Adunapehl the ringwraith
Aiglos
Akhorahil
Alatar the hunter
Amon hen (metw)
Amon hen (mele)
an unexpected party
anarin
Ancient black axe
Army of the dead
ash mountains
back to the fray
bairanax
balrog of moria
barrow-wight (metw)
barrow-wight (mele)
beasts of the wood
beorning skin-changers
bill the pony
black breath
black horse
black mace
black rider
blackbole
book of mazarbul
bow of alatar
bow of dragon-horn
bow of the galadrim
by the ringwraith 's word
carn dum (metw)
carn dum (mele)
cave troll
cave worm (metw)
cave worm (mele)
cave-drake (metw)
cave-drake (mele)
clear skies
corsair of umbar
cram
creature of an older world
crept alonf carefully
daelomin
Dale (metd)
Dale (mele)
Dead marshes (metw)
Dead marshes (mele)
Delver's harvest
Dol amroth (metw)
Dol amroth (mele)
Dol Guldur (metw)
Dol Guldur (mele)
dragon-lore
dreams of lore
Durin's axe
Dwar of waw
dwar the ringwraith
dwarven light-stone
dwarven travelers
eagle-mounts
eacaraxe ahunt
earth-tremors
edhellond (metw)
edhellond (mele)
elf-lord revealed in wrath
elf-song
emerald of doriath
emerald of the mariner
farmer maggot
fell rider
fellowship
flies and spiders
foul-smelling paste
galadhrim
gems of arda
ghan-buri-ghan
gif of comprehension
gladden fields (metw)
gladden fields (mele)
glance of arien
gobel mirlond (metw)
gobel mirlond (mele)
goldberry
gollum
gondmaeglom (metw)
gondmaeglom (mele)
great bats
great-road
grey havens (metw)
grey havens (meas)
guarded haven
gwaihir
healing herbs
heart grown cold
herb-lore
hoarmurath of dir
hoarmurath the ringwraith
hobbit-lore
horn of anor
I'll be at your heels
I'll report you
Ice-drake
Indur dawndeath
Indur the ringwraith
irefull flames
iron-road
Isles of the dead that live (meas)
jewel of beleriand
Khamul the easterling
khamul the ringwraith
king under the mountain
lake-town (metw)
lake-town (mele)
landroval
lapse of will
leaflock
legendary hoard
lindion the oronin
liquid fire
Lobelia Sackville-baggins
Lond galen (metw)
Lond Galen (mele)
lore of the ages
Lorien (metw)
Lorien (meas)
magical harp
maker's map
many-colored robes
map to mithril
mathom lore
minas tirith (metw)
minas tirith (mele)
miruvor
mistress lobelia
misty mountains
mithril
morgul-rats
moria (metw)
moria (mele)
mount-doom (metw)
mount-doom (mele)
mount gram (metw)
mount gram (mele)
mount gundabad (metw)
mount gundabad (mele)
My precious
necklace of girion
necklace of silver and pearls
neeker-breekers
nenselde the wingild
news of the shire
no more nonsense
noble hound
noble steed
noldo lantern
old treasure
om-buri-om
orc-draughts
orc-liquor
orders from lugburz
orders from the great demon
Pallando the soul-keeper
paths of the dead
pelargir (metw)
pelargir (mele)
pierced by many wound
plague
pon-ora-pon
potion of prowess
praise to elbereth
quickbeam
radagast the tamer
radagast's black bird
records unread
red book of the westmarch (metw)
red book of the westmarch (mele)
regiment of black crows
ren the unclean
river (metw)
river (mele)
roac the raven
sacrifice of form
sand-drake
scorba
scroll of isildur (metw)
scroll of isildur (mele)
secret book
seized by terror
shadowfax
shrel-kain (metw)
shrel-kain (mele)
skies of fire
skinbark
sleepless malice
smart and secret
smaug
sneakin
song of the lady
star of high hope
star-glass
strange ration
strider
sun
swag
tales of the hunt
tharbad (metd)
tharbad (mele)
that ain't no secret
that's been heard before tonight
the arkenstone (metw)
the arkenstone (mele)
the ash mountain deeps
The drowning-deeps (meba)
the iron crown (metw)
the iron crown (mele)
the iron-deeps (meba)
the lonely mountain (metw)
the lonely mountain (mele)
the misty mountain deeps
the mithril-coat (metw)
the mithril-coat (mele)
The mountains of shadow deeps
The names among them
The one ring (metw)
The one ring (mele)
the reach of ulmo
The rusted-deeps (meba)
the sulfur-deeps (metw)
the sulfur-deeps (meas)
the sulfur-deeps (meba)
The undeeps of anduin
the under-court (meba)
the under-gates (metw)
the under-gates (mele)
the under-vaults (meba)
the warg-king
the way is shut
the white mountain cavern-ways
the wind-deeps (meba)
the windlord found me
thrall of the voice
thror's map (metd)
thror's map (meas)
to fealty sworn
tom bombadil
torque of hues
treebeard
twice-baked cakes
uvatha the horseman
vein of arda
war-warg
war-wolf
waybread
winds of wrath
winged change-master
witch-king of angmar
wizard's laughter
wizard's ring
wormsbane
zarak dum (metw)
zarak dum (mele)

**Comment by usmcgeek** [comment]
Hi! Thank you!  I had only intended to do the released cards originally.  I was going to do the DC versions as well - but I just ran out of steam ultimately.  In any event - you can easily do these versions.  If you check the other for the [Card Editor](https://github.com/usmcgeek/meccg).  That will let you knock these out.  All the set files are included over there also, so you can just open up the set and edit the original card and then export the image.  Please do note that you do not want to use that with the original Magic Set Editor if you have it - I made that custom fork for MECCG and hardcoded support for 300 dpi export into it (plus tweaked all the MECCG styles and stuff to support the remaster).  I would expect that you could download, play with / figure it out - and update all these in an hour or two most likely.

**Comment by thenamelessthing** [comment]
ok cool! I will give it a try this weekend!  I was wondering, did you try to print some with MPC? What is the result? Is it better with the remastered or the restored style?

**Comment by usmcgeek** [comment]
I have printed with MPC using the black bordered. Works great!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thenamelessthing** [comment]
Can you share a picture of the result?

It is possible to choose fonts in MSEditor?

**Comment by usmcgeek** [comment]
Wow - sorry I missed this!  No, that should be just fine without those.
