### ISSUE TITLE
Some corrections on The Lidless Eye remastered_style cards

### ISSUE THREAD

**Issue by maxocub** [usmcgeek/mer#18]
Thank you for this repo!
I don't have a windows computer so I cannot make these corrections myself.

This card is a resource but have the hazard background:
https://github.com/usmcgeek/mer/blob/master/data/remastered_style/mele/Some%20Secret%20Art%20of%20Flame.png

This card have some repeated text:
https://github.com/usmcgeek/mer/blob/master/data/remastered_style/mele/We%20Have%20Come%20to%20Kill.png

**Comment by usmcgeek** [comment]
Fixed and uploaded - thank you!

**Comment by maxocub** [comment]
Great! Thank you!
